PrimerMvcNetCore/Models/ErrorViewModel.cs
namespace PrimerMvcNetCore.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PrimerMvcNetCore/Models/FilaTablaMultiplicar.cs
using Microsoft.AspNetCore.Mvc;

namespace PrimerMvcNetCore.Models
{
    public class FilaTablaMultiplicar
    {
        public string Operacion { get; set; }
        public int Resultado { get; set; }
    }
}

PrimerMvcNetCore/Models/Persona.cs
namespace PrimerMvcNetCore.Models
{
    public class Persona
    {
        public string Nombre { get; set; }
        public string Email { get; set; }
        public int Edad { get; set; }
    }
}

PrimerMvcNetCore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PrimerMvcNetCore.Models;
using System.Diagnostics;

namespace PrimerMvcNetCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PrimerMvcNetCore/Controllers/InformacionController.cs
using Microsoft.AspNetCore.Mvc;
using PrimerMvcNetCore.Models;

namespace PrimerMvcNetCore.Controllers
{
    public class InformacionController : Controller
    {   
        public IActionResult Index()
        {
            return View();
        }

       //Siempre tiene que haber un get

        public IActionResult VistaControladorPost()
        {
            return View();
        }
        [HttpPost]
        public IActionResult VistaControladorPost(Persona persona, string aficiones)
        {
            //Algunos vienen de un modle y otro ahi creado no hace falta que sean todos iguales
            ViewData["DATOS"] = "Nombre: " + persona.Nombre + " Correo: " + persona.Email + " Edad: " + persona.Edad + ", Aficiones: " + aficiones;
            return View();
        }

        public IActionResult ControladorVista()
        {
            //Vamos a enviar informacion simple a nuestra vista
            ViewData["NOMBRE"] = "Alumno";
            ViewData["EDAD"] = 25;
            ViewBag.DiaSemana = "Lunes";
            ViewData["DIASEMANA"] = "Mañana martes!!"; //Se comen con el ultimo y hacen lo mismo en el controlador da igual cual pongas

            //Con Model
            Persona persona = new Persona();
            persona.Nombre = "Persona Model";
            persona.Email = "laktcuento@gmail.com";
            persona.Edad = 777;
            return View(persona); //IMPORTANTE CON MODEL AÑADIR AL RETURN EL PROPIO MDEL
        }

        //VAMOS A RECIBIR DOS PARAMETROS
        public IActionResult VistaControladorGet(string app, System.Nullable<int> version)          
        {   
            //Ahora la version es opcional gracias al system nullable de la declaraicon de arriba
            if (version is null)
            {

            }
            //Dibujamos en la vista los parametros recibidos
            ViewData["DATOS"] = "Aplicacion " + app + " , Version: " + version.GetValueOrDefault();
         
            return View();
        }
    }
}

PrimerMvcNetCore/Controllers/MatematicasController.cs
using Microsoft.AspNetCore.Mvc;
using PrimerMvcNetCore.Models;

namespace PrimerMvcNetCore.Controllers
{
    public class MatematicasController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult SumarNumerosGet(int numero1, int numero2)
        {
            int suma = numero1 + numero2;
            ViewData["RESULTADO"] = "El resultado de " + numero1 + " y " + numero2 + " es: " + suma;
            return View();
        }
        public IActionResult SumarNumerosPost()
        {
            return View();
        }
        [HttpPost]
        public IActionResult SumarNumerosPost(int numero1, int numero2)
        {
            int suma = numero1 + numero2;
            ViewData["RESULTADO"] ="La suma de " + numero1 + " y "+ numero2+ " es " + suma;
            return View();
        }

        public IActionResult ConjeturaCollatz()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ConjeturaCollatz(int numero)
        {   
            //Declaramos un model apra enviarlo a la vista
            List<int> numeros = new List<int>();
            while(numero != 1)
            {
                if(numero % 2 == 0)
                {
                    numero = numero / 2;
                }
                else
                {
                    numero = numero * 3 + 1;
                }
                numeros.Add(numero);
            }
            //Devolvemos el model a la vista
            return View(numeros);
        }

        public IActionResult TablaMultiplicarSimple()
        {
            return View();
        }

        [HttpPost]
        public IActionResult TablaMultiplicarSimple(int numero)
        {
            List<int> resultados = new List<int>();
            for (int i = 1; i <= 10; i++)
            {
                int operacion = numero * i;
                resultados.Add(operacion);
            }
            return View(resultados);
        }

        public IActionResult TablaMultiplicarModel()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult TablaMultiplicarModel(int numero)
        {
            List<FilaTablaMultiplicar> resultados = new List<FilaTablaMultiplicar>();
            for (int i = 0; i <= 10; i++)
            {
                string operacion = numero + " * " + i;
                int result = numero * i;

                FilaTablaMultiplicar fila = new FilaTablaMultiplicar();
                fila.Resultado = result;
                fila.Operacion = operacion;
                resultados.Add(fila);
            }
            return View(resultados);
        }
    }
}

PrimerMvcNetCore/Controllers/PruebaController.cs
using Microsoft.AspNetCore.Mvc;

namespace PrimerMvcNetCore.Controllers
{
    public class PruebaController : Controller
    {
        public IActionResult PrimeraPagina()
        {   
            return View();
        }
    }
}

PrimerMvcNetCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PrimerMvcNetCore/Views/Informacion/ControladorVista.cshtml
@model Persona 



<h1 style="color:blue">Informacion controlador --> Vista</h1>

<h2 style="color:lightblue"> @Model.Nombre , @Model.Email, @Model.Edad</h2>

<h2 style="color:red"> Nombre: @ViewData["NOMBRE"]</h2>

<h2 style="color:green"> Edad: @ViewData["EDAD"]</h2>

<h2 style="color:purple"> Día semana: @ViewData["DIASEMANA"] / @ViewBag.DiaSemana</h2>

PrimerMvcNetCore/Views/Informacion/Index.cshtml
<h1>Menu Informacion</h1>
<ul>
    <li>
        <a asp-controller="Informacion"
         asp-action="ControladorVista">
            Controlador --> Vista
        </a>
    </li>
    <li>
        @Html.ActionLink("Vista --> Controller GET", "VistaControladorGet", "Informacion", new {app = "Mvc Net Core", version = 7})
    </li>
    <li>
        @Html.ActionLink("Vista --Controller GET sin parametros", "VistaControladorGet", "Informacion")
    </li>
    <li>
        @Html.ActionLink("Vista --Controller POST", "VistaControladorPost", "Informacion")
    </li>
</ul>

PrimerMvcNetCore/Views/Informacion/VistaControladorGet.cshtml
<h1>
    Informacion Vista ----> controlador
</h1>

<h2 style="color:blue">
    @ViewData["DATOS"]
</h2>

PrimerMvcNetCore/Views/Informacion/VistaControladorPost.cshtml
<h1>
    Vista --> Controller POST
</h1>

<form method="post">
    <label>Nombre: </label>
    <input type="text" name="nombre" class="form-control"/>
    <label>Email: </label>
    <input type="text" name="email" class="form-control" />
    <label>Edad: </label>
    <input type="text" name="edad" class="form-control" />
    <label>Aficiones: </label>
    <input type="text" name="aficiones" class="form-control" />
    <button class=" btn btn-info">Enviar datos</button>
</form>

<h1 style="color:purple">@ViewData["DATOS"]</h1>

PrimerMvcNetCore/Views/Matematicas/ConjeturaCollatz.cshtml
@model List<int>


<h1>Conjetura collatz</h1>

<form method="post">
    <label>Introduce un número</label>
    <input type="text" name="numero" class="form-control" />
    <button class="btn btn-success">Conjetura Collatz</button>
</form>
<hr />

@if(Model != null)
{
    <ul>
        @foreach (int num in Model)
        {
            <li>@num</li>
        }
    </ul>
}

PrimerMvcNetCore/Views/Matematicas/Index.cshtml
<h1>Vista matematicas</h1>

<ul>
    <li>
        @Html.ActionLink("Vista Suma de matematicas 33 y 22", "SumarNumerosGet", "Matematicas", new{numero1 = 33, numero2 = 22})
    </li>
    <li>
        @Html.ActionLink("Vista Realizacion suma", "SumarNumerosPost", "Matematicas")
    </li>
    <li>
        @Html.ActionLink("Conjetura Collatz", "ConjeturaCollatz", "Matematicas")
    </li>
    <li>
        @Html.ActionLink("Tabla Multpliclar", "TablaMultiplicarSimple", "Matematicas")
    </li>
    <li>
        @Html.ActionLink("Tabla Multpliclar Model", "TablaMultiplicarModel", "Matematicas")
    </li>
</ul>

PrimerMvcNetCore/Views/Matematicas/SumarNumerosGet.cshtml
<h1>Suma de numeros</h1>

<h2 style="color:purple">Resultado: @ViewData["RESULTADO"]</h2>

PrimerMvcNetCore/Views/Matematicas/SumarNumerosPost.cshtml
<h1>
    Suma de numeros
</h1>

<form method="post">
    <label>Numero 1: </label>
    <input type="number" name="numero1" class="form-control" />
    <label>Numero 2: </label> 
    <input type="number" name="numero2" class="form-control" />
    <button class=" btn btn-info">Sumar numeros</button>
</form>

<h2 style="color:purple">Resultado: @ViewData["RESULTADO"]</h2>

PrimerMvcNetCore/Views/Matematicas/TablaMultiplicarModel.cshtml
@model List<FilaTablaMultiplicar>

<h1>Tabla multiplicar model</h1>
<form method="post">
    <label>Número: </label>
    <input / type="number" name="numero" class="form-control">
    <button class="btn btn-outline-danger">
        Tabla Multplicar
    </button>
</form>

@if (Model != null)
{
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Operacion</th>
                <th>Resultados</th>
            </tr>
        </thead>
        <tbody>
            @foreach (FilaTablaMultiplicar fila in Model)
            {
                <tr>
                    <td>@fila.Operacion</td>
                    <td>@fila.Resultado</td>
                </tr>
            }
        </tbody>
    </table>
}

PrimerMvcNetCore/Views/Matematicas/TablaMultiplicarSimple.cshtml
@model List<int>

<h1>Tabla multiplicar Simple</h1>

<form method="post">
    <label>Número: </label>
    <input / type="number" name="numero" class="form-control">
    <button class="btn btn-outline-danger">
        Tabla Multplicar
    </button>
</form>
@if (Model != null)
{
    <ul>
        @foreach (int numero in Model)
        {
            <li>@numero</li>
        }
    </ul>
}

PrimerMvcNetCore/Views/Prueba/PrimeraPagina.cshtml
@*
    COMENTARIOS EN RAZOR
*@

DECLARACION DE VARIABLES A NIVEL DE PAGINA

@{
    //VARIABLES LOCALES DE PAGINA
    //TODO ESTO ES CODIGO C#
    int valor = 15;
    string texto = "Hoy es lunes";
    valor += 1;
    texto = texto.ToUpper();
}

DIBUJAR VARIABLES

<h2 style="color:red">Texto @texto, Número: @valor</h2>

CODIGO LOGICO

@if (valor >= 0)
{
    //codigo c#
    texto = "POSITIVO";
    <h2 style="color:green">@texto</h2>
}else
{
    texto = "NEGATIVO";
    <h2 style="color:purple">@texto</h2>
}

<h1 style="color:blue">
    Mi primera pagina MVC Net Core!!!
</h1>

PrimerMvcNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PrimerMvcNetCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PrimerMvcNetCore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PrimerMvcNetCore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Prueba" asp-action="PrimeraPagina">
                                Mi primera pagina
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Informacion" asp-action="Index" class="nav-link">
                                Información
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Matematicas" asp-action="Index" class="nav-link">
                                Matematicas
                            </a>
                        </li>                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PrimerMvcNetCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>